# Use a imagem oficial do Node.js mais recente
FROM node:20.18.0-alpine

# Instale o bash e o xsel
RUN apk update && apk add bash xsel

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie os arquivos de dependências e o package.json para o container
COPY package*.json ./

# Instale as dependências da aplicação
RUN npm install

# Copie todo o código da aplicação para o container
COPY . .

# Execute o build da aplicação React com TypeScript
RUN npm run build

# Instale o pacote 'serve' globalmente para servir a aplicação
RUN npm install -g serve

# Copie o script de inicialização
COPY start.sh .

# Torne o script executável
RUN chmod +x start.sh

# Exponha a porta 3000 para servir a aplicação
EXPOSE 3000

# Comando para executar o script de inicialização
CMD ["./start.sh"]
